---
title: "Quickstart"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Quickstart}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Prepare a sample dataset for Naive Bayes
```{r setup}
library(mvtnorm)
set.seed(1)

# sample sizes
n_labeled <- 300
n_unlabeled <- 3000
n_feats <- 10

# mean values and covariance matrices
mu <- c(-10, -5, 0, 5, 10) %*% t(rep(1, n_feats))
rownames(mu) <- 1:5
sigma <- diag(rep(1,n_feats))
```

```{r simulate data}
# specify number of labeles / unlabeled samples per class
labeled_classes <- rep(c(2, 3), each = n_labeled / 2)
unlabeled_classes <- rep(1:5, each = n_unlabeled / 5)
num_sample <- c(table(labeled_classes), table(unlabeled_classes))

# simulate X, ytrue and y
X <- c()
for(i in 1:length(num_sample)){
  X <- rbind(X, rmvnorm(num_sample[i], mu[names(num_sample)[i],], sigma))
}
y <- rep(c(1, 2, NA), c(table(labeled_classes), length(unlabeled_classes)))
ytrue <- rep(names(num_sample), num_sample)
```

## Train SSC-UC model
```{r train}
library(SSCUC)

# specify dataset and formula
data <- as.data.frame(cbind(X, y))
formula <- y ~ V1 + V2 - 1

# train model
model <- SSC(formula, data, naive = TRUE)
summary(model)
```

## Predict and evaluate unlabeled data using SSC-UC model
```{r predict}
# predict on unlabeled data
pred <- predict(model, newdata = subset(data, is.na(y)), type = "class")
```

### Evaluate in full confusion matrix (multiple new classes)
```{r evaluate1}
library(caret)
library(knitr)

# specify levels
levels <- sort(union(unique(pred), unique(ytrue)))

kable(confusionMatrix(
  reference = factor(ytrue[is.na(y)], levels = levels), 
  data = factor(pred, levels = levels))$table[sort(unique(pred)),sort(unique(ytrue))]
)
```

### Evaluate in reduced confusion matrix (all new classes as class "U")
```{r evaluate2}
# set all new class labels to "U"
pred[!pred %in% unique(ytrue)] <- "U"

# specify levels
levels <- sort(union(unique(pred), unique(ytrue)))

kable(confusionMatrix(
  reference = factor(ytrue[is.na(y)], levels = levels), 
  data = factor(pred, levels = levels))$table[sort(unique(pred)),sort(unique(ytrue))]
)
```
